language: java
matrix:
  include:
  - os: linux
    jdk: openjdk8
  - os: osx
script: mvn test && mvn clean verify -PintegrationTests
deploy:
  skip_cleanup: true
  provider: script
  script: ./travis/deploy.sh
  on:
    branch: master
    tags: true
env:
  global:
  - secure: YBdTKc5juLQGzurNJcoEuzkUEjSfavEJa3z1NmaNFISDswI3DG4eHsBrNJiBkEYHP0RhZxvGY+xpciyH4vthMQczs7EpZrMHqr9sOovCizkVXxI/nUlCTWlWTrQEnoyoAj18cDC0M2pJ5tgQoId+TwdySLPd8+aGLOF6uTR0V9U=
  - secure: T9SClKKwe9iTJq94L/XxZBR6XGuZo5bn6+p5t97K/23VQb+1w3HXRcqDiR/kFnZa74KtdARc4s+dsTPz18Y6eiraybW7zE00rqWnLNg0pRcoaXwTSPqm2NpJA1PhnG6Y7pCbNNtJFB4WBa8lmUqrIwgEy1rE8gyJlTfAoDgrNEw=
  - secure: J239znDCwf91fC9oMvPSw9xb+iQhbGaVcP4p1l82QKhcDHnQ8nYirT0DFeMVu8XUK5IaaxmvAsKh8ri58HbUCJwOz1F3VZ99rNM8p5/63KC+89ZvPKxjHNQHCYyKc9x/XdzOy+n1cTbFFgGAFOXJNyU2AtWkUGjP+8UILiPWBuo=
addons:
  sonarcloud:
    organization: "monity"
    token:
      secure: 09b8441760fd47182772436e819f068037ef9677 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
